package com.api.isswhu.demo.dao;

import com.api.isswhu.demo.domain.mysql.Imageinfo;

import java.util.List;

public interface ImageinfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table imageinfo
     *
     * @mbggenerated Mon Mar 12 13:20:40 CST 2018
     */
    int insert(Imageinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table imageinfo
     *
     * @mbggenerated Mon Mar 12 13:20:40 CST 2018
     */
    int insertSelective(Imageinfo record);
    
    int deleteByImageName(String imageName);
    
    List<Imageinfo> selectByImageName(String imageName);
}
