package com.api.isswhu.demo.dao;

import com.api.isswhu.demo.domain.mysql.Serviceinfo;

import java.util.List;

public interface ServiceinfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table serviceinfo
     *
     * @mbggenerated Tue Mar 06 15:12:25 CST 2018
     */
    int deleteByPrimaryKey(String serviceid);
    
    int deleteByServiceName(String serviceName);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table serviceinfo
     *
     * @mbggenerated Tue Mar 06 15:12:25 CST 2018
     */
    int insert(Serviceinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table serviceinfo
     *
     * @mbggenerated Tue Mar 06 15:12:25 CST 2018
     */
    int insertSelective(Serviceinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table serviceinfo
     *
     * @mbggenerated Tue Mar 06 15:12:25 CST 2018
     */
    Serviceinfo selectByPrimaryKey(String serviceid);
    
    Serviceinfo selectByPort(String  port);
    
    Serviceinfo selectByMonitorId(String monitorId);
    
    Serviceinfo selectByServiceName(String monitorId);
    
    List<Serviceinfo> selectByImageName(String imageName);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table serviceinfo
     *
     * @mbggenerated Tue Mar 06 15:12:25 CST 2018
     */
    int updateByPrimaryKeySelective(Serviceinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table serviceinfo
     *
     * @mbggenerated Tue Mar 06 15:12:25 CST 2018
     */
    int updateByPrimaryKey(Serviceinfo record);
}
