package com.api.isswhu.demo.domain.mysql;

public class Imageinfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column imageinfo.imageId
     *
     * @mbggenerated Mon Mar 12 13:20:40 CST 2018
     */
    private String imageid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column imageinfo.imageName
     *
     * @mbggenerated Mon Mar 12 13:20:40 CST 2018
     */
    private String imagename;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column imageinfo.tag
     *
     * @mbggenerated Mon Mar 12 13:20:40 CST 2018
     */
    private String tag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column imageinfo.filePath
     *
     * @mbggenerated Mon Mar 12 13:20:40 CST 2018
     */
    private String filepath;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column imageinfo.imageId
     *
     * @return the value of imageinfo.imageId
     *
     * @mbggenerated Mon Mar 12 13:20:40 CST 2018
     */
    public String getImageid() {
        return imageid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column imageinfo.imageId
     *
     * @param imageid the value for imageinfo.imageId
     *
     * @mbggenerated Mon Mar 12 13:20:40 CST 2018
     */
    public void setImageid(String imageid) {
        this.imageid = imageid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column imageinfo.imageName
     *
     * @return the value of imageinfo.imageName
     *
     * @mbggenerated Mon Mar 12 13:20:40 CST 2018
     */
    public String getImagename() {
        return imagename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column imageinfo.imageName
     *
     * @param imagename the value for imageinfo.imageName
     *
     * @mbggenerated Mon Mar 12 13:20:40 CST 2018
     */
    public void setImagename(String imagename) {
        this.imagename = imagename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column imageinfo.tag
     *
     * @return the value of imageinfo.tag
     *
     * @mbggenerated Mon Mar 12 13:20:40 CST 2018
     */
    public String getTag() {
        return tag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column imageinfo.tag
     *
     * @param tag the value for imageinfo.tag
     *
     * @mbggenerated Mon Mar 12 13:20:40 CST 2018
     */
    public void setTag(String tag) {
        this.tag = tag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column imageinfo.filePath
     *
     * @return the value of imageinfo.filePath
     *
     * @mbggenerated Mon Mar 12 13:20:40 CST 2018
     */
    public String getFilepath() {
        return filepath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column imageinfo.filePath
     *
     * @param filepath the value for imageinfo.filePath
     *
     * @mbggenerated Mon Mar 12 13:20:40 CST 2018
     */
    public void setFilepath(String filepath) {
        this.filepath = filepath;
    }
}