package com.api.isswhu.demo.domain.mysql;

public class Serviceinfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column serviceinfo.serviceId
     *
     * @mbggenerated Tue Mar 06 15:12:25 CST 2018
     */
    private String serviceid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column serviceinfo.serviceName
     *
     * @mbggenerated Tue Mar 06 15:12:25 CST 2018
     */
    private String servicename;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column serviceinfo.monitorId
     *
     * @mbggenerated Tue Mar 06 15:12:25 CST 2018
     */
    private String monitorid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column serviceinfo.imageName
     *
     * @mbggenerated Tue Mar 06 15:12:25 CST 2018
     */
    private String imagename;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column serviceinfo.replica
     *
     * @mbggenerated Tue Mar 06 15:12:25 CST 2018
     */
    private Integer replica;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column serviceinfo.port
     *
     * @mbggenerated Tue Mar 06 15:12:25 CST 2018
     */
    private String port;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column serviceinfo.serviceId
     *
     * @return the value of serviceinfo.serviceId
     *
     * @mbggenerated Tue Mar 06 15:12:25 CST 2018
     */
    public String getServiceid() {
        return serviceid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column serviceinfo.serviceId
     *
     * @param serviceid the value for serviceinfo.serviceId
     *
     * @mbggenerated Tue Mar 06 15:12:25 CST 2018
     */
    public void setServiceid(String serviceid) {
        this.serviceid = serviceid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column serviceinfo.serviceName
     *
     * @return the value of serviceinfo.serviceName
     *
     * @mbggenerated Tue Mar 06 15:12:25 CST 2018
     */
    public String getServicename() {
        return servicename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column serviceinfo.serviceName
     *
     * @param servicename the value for serviceinfo.serviceName
     *
     * @mbggenerated Tue Mar 06 15:12:25 CST 2018
     */
    public void setServicename(String servicename) {
        this.servicename = servicename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column serviceinfo.monitorId
     *
     * @return the value of serviceinfo.monitorId
     *
     * @mbggenerated Tue Mar 06 15:12:25 CST 2018
     */
    public String getMonitorid() {
        return monitorid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column serviceinfo.monitorId
     *
     * @param monitorid the value for serviceinfo.monitorId
     *
     * @mbggenerated Tue Mar 06 15:12:25 CST 2018
     */
    public void setMonitorid(String monitorid) {
        this.monitorid = monitorid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column serviceinfo.imageName
     *
     * @return the value of serviceinfo.imageName
     *
     * @mbggenerated Tue Mar 06 15:12:25 CST 2018
     */
    public String getImagename() {
        return imagename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column serviceinfo.imageName
     *
     * @param imagename the value for serviceinfo.imageName
     *
     * @mbggenerated Tue Mar 06 15:12:25 CST 2018
     */
    public void setImagename(String imagename) {
        this.imagename = imagename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column serviceinfo.replica
     *
     * @return the value of serviceinfo.replica
     *
     * @mbggenerated Tue Mar 06 15:12:25 CST 2018
     */
    public Integer getReplica() {
        return replica;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column serviceinfo.replica
     *
     * @param replica the value for serviceinfo.replica
     *
     * @mbggenerated Tue Mar 06 15:12:25 CST 2018
     */
    public void setReplica(Integer replica) {
        this.replica = replica;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column serviceinfo.port
     *
     * @return the value of serviceinfo.port
     *
     * @mbggenerated Tue Mar 06 15:12:25 CST 2018
     */
    public String getPort() {
        return port;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column serviceinfo.port
     *
     * @param port the value for serviceinfo.port
     *
     * @mbggenerated Tue Mar 06 15:12:25 CST 2018
     */
    public void setPort(String port) {
        this.port = port;
    }
}