
server:
  port: 8080

spring:
    datasource:
        name: test
        url: jdbc:mysql://localhost:3306/dockeriss?useUnicode=true&amp;characterEncoding=utf8&amp;autoReconnect=true&amp;autoReconnectForPools=true&amp;zeroDateTimeBehavior=convertToNull
        username: root
        password: 123456*a
        # \u4F7F\u7528druid\u6570\u636E\u6E90
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20
mybatis:
    mapper-locations: classpath:mapper/*.xml
    type-aliases-package: com.api.isswhu.demo.domain.mysql
#docker
docker:
    config:
        url: http://172.16.17.131:2375
        userName: fzydocker
        pswd: FUzhenyu1996
        #监控服务的 镜像名称
        imageName: busybox
        registryIp: 172.16.17.141
        registryPort: 5000
        visualizerName: viz
        net: overAttach
        networkID: 42t6l1prpupppx9xxexllnsbq
